//
// Created by glebo on 20.04.2026.
//

#ifndef SECURE_TOURISM_DB_SYSTEM_IENCRYPTIONSERVICE_H
#define SECURE_TOURISM_DB_SYSTEM_IENCRYPTIONSERVICE_H



class IEncryptionService {

};



#endif //SECURE_TOURISM_DB_SYSTEM_IENCRYPTIONSERVICE_H
